# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
        
      - name: Create assets folder
        run: mkdir -p assets
        
      - name: Generate Snake
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: shubh4m-2k04
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Commit and push the changes
      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          commit_message: ":snake: Updates Snake Contribution Animation"
          commit_user_name: shubham
          commit_user_email: theshubham1412@gmail.com
          commit_author: Shubham Pawar <theshubham1412@gmail.com>
